### ISSUE TITLE
Referencia errónea

### ISSUE THREAD

**Issue by sergioviera** [dds-frd-utn/TP1-EMNI#2]
https://github.com/dds-frd-utn/TP1-EMNI/blob/c1da28c00b9e56988f92e585b8fe12a2bb573603/Documents/NetBeansProjects/EmniApp/src/main/java/utn/frd/emniapp/entity/Cuenta.java#L44

Como se ven todas las inversiones en un sólo campo entero?

**Comment by MNico99** [comment]
esta todo solucionado en el otro repo https://github.com/dds-frd-utn/TP1-TP2-EMNI-BANK
